CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(254) NOT NULL,
    display_name VARCHAR(40) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(16) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE chat_rooms (
    id VARCHAR(36) NOT NULL,
    name VARCHAR(80) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_chat_rooms_name UNIQUE (name),
    CONSTRAINT fk_chat_rooms_creator FOREIGN KEY (created_by) REFERENCES users(id)
);
CREATE INDEX idx_chat_rooms_created_by ON chat_rooms (created_by);

CREATE TABLE room_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    room_id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    joined_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    last_read_at TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_membership_room_user UNIQUE (room_id, user_id),
    CONSTRAINT fk_membership_room FOREIGN KEY (room_id) REFERENCES chat_rooms(id),
    CONSTRAINT fk_membership_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_membership_user_room ON room_memberships (user_id, room_id);

CREATE TABLE chat_messages (
    id VARCHAR(36) NOT NULL,
    room_id VARCHAR(36) NOT NULL,
    sender_id BIGINT NOT NULL,
    client_message_id VARCHAR(36) NOT NULL,
    content VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_message_sender_client_id UNIQUE (sender_id, client_message_id),
    CONSTRAINT fk_message_room FOREIGN KEY (room_id) REFERENCES chat_rooms(id),
    CONSTRAINT fk_message_sender FOREIGN KEY (sender_id) REFERENCES users(id)
);
CREATE INDEX idx_message_room_time_id ON chat_messages (room_id, created_at, id);
CREATE INDEX idx_message_sender_time ON chat_messages (sender_id, created_at);

CREATE TABLE message_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    state VARCHAR(16) NOT NULL DEFAULT 'SENT',
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_receipt_message_user UNIQUE (message_id, user_id),
    CONSTRAINT fk_receipt_message FOREIGN KEY (message_id) REFERENCES chat_messages(id),
    CONSTRAINT fk_receipt_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_receipt_user_state ON message_receipts (user_id, state);

CREATE TABLE chat_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    payload TEXT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    published_at TIMESTAMP(6),
    PRIMARY KEY (id)
);
CREATE INDEX idx_outbox_pending ON chat_outbox (published_at, id);
