ALTER TABLE chat_rooms
    ADD COLUMN is_public BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN invite_code VARCHAR(36) NULL;

UPDATE chat_rooms SET invite_code = gen_random_uuid()::text WHERE invite_code IS NULL;

ALTER TABLE chat_rooms
    ALTER COLUMN invite_code SET NOT NULL;

ALTER TABLE chat_messages
    ADD COLUMN edited_at TIMESTAMP(6);

CREATE TABLE room_bans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    room_id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    banned_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_room_ban_room_user UNIQUE (room_id, user_id),
    CONSTRAINT fk_room_ban_room FOREIGN KEY (room_id) REFERENCES chat_rooms(id),
    CONSTRAINT fk_room_ban_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_room_ban_admin FOREIGN KEY (banned_by) REFERENCES users(id)
);
